spring:
  thymeleaf:
#    enabled: true  #开启thymeleaf视图解析
    cache: false  #是否使用缓存
#    mode: HTML5  #严格的HTML语法模式
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo?useSSL=true&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    dbcp:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200
  liquibase:
    change-log: classpath:/liquibase/master.xml
    user: root
    password: root
    url: jdbc:mysql://localhost:3306/demo?useSSL=true&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    enabled: true

# 配置slq打印日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  typeEnumsPackage: com.tniu.imall.admin.type
  global-config: #配置逻辑删除
    db-config:
      logic-delete-value: 0 # 逻辑已删除值(默认为 0)
      logic-not-delete-value: 1 # 逻辑未删除值(默认为 1)