CREATE DATABASE IF NOT EXISTS blog DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

USE blog; 

CREATE TABLE IF NOT EXISTS USER(
	ID INT(11) NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(64) NOT NULL,
	AGE int(4) NULL DEFAULT NULL,
	ADDRESS VARCHAR(64) NULL DEFAULT NULL,
	PHONE_NUMBER VARCHAR(11) NULL DEFAULT NULL,
	ID_CARD VARCHAR(19) NULL DEFAULT NULL,
	CREATE_DATE DATETIME(6) NULL DEFAULT NULL,
	EDIT_DATE DATETIME(6) NULL DEFAULT NULL,
	PRIMARY KEY (ID)
) DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

CREATE TABLE IF NOT EXISTS BLOG (
	ID INT(11) NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(64) NOT NULL,
	CREATE_DATE DATETIME(6) NULL DEFAULT NULL,
	CREATE_USER INT(11) NULL DEFAULT NULL,
	EDIT_DATE DATETIME(6) NULL DEFAULT NULL,
	EDIT_USER INT(11) NULL DEFAULT NULL,
	CONTENT VARCHAR(1024) NULL DEFAULT NULL,
	STATUS VARCHAR(32) NULL DEFAULT NULL,
	PRIMARY KEY (ID),
	CONSTRAINT `FK_BLOG_CREATE_USER_ID` FOREIGN KEY (`CREATE_USER`) REFERENCES `USER` (`ID`) ON UPDATE NO ACTION ON DELETE NO ACTION,
	CONSTRAINT `FK_BLOG_EDIT_USER_ID` FOREIGN KEY (`EDIT_USER`) REFERENCES `USER` (`ID`) ON UPDATE NO ACTION ON DELETE NO ACTION
) 
DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

INSERT INTO USER(NAME, AGE, ADDRESS, PHONE_NUMBER, ID_CARD, CREATE_DATE, EDIT_DATE) 
VALUES('jeck001', 21, 'XXXXXXXXX', '12345678901', '123456789987654321', NOW(), NOW()),
('jeck002', 22, 'XXXXXXXXX', '12345678901', '123456789987654321', NOW(), NOW()),
('jeck003', 23, 'XXXXXXXXX', '12345678901', '123456789987654321', NOW(), NOW()),
('jeck004', 24, 'XXXXXXXXX', '12345678901', '123456789987654321', NOW(), NOW());

INSERT INTO BLOG(NAME, CREATE_DATE, CREATE_USER, EDIT_DATE, EDIT_USER, CONTENT) 
VALUES('GOOD JOB', NOW(), 1, NOW(), 2, 'xxxxxxxxxxxxxxxxxxxxxxx'),
('GOOD JOB1', NOW(), 1, NOW(), 2, 'xxxxxxxxxxxxxxxxxxxxxxx'),
('GOOD JOB2', NOW(), 1, NOW(), 2, 'xxxxxxxxxxxxxxxxxxxxxxx'),
('GOOD JOB3', NOW(), 1, NOW(), 2, 'xxxxxxxxxxxxxxxxxxxxxxx'),
('GOOD JOB4', NOW(), 1, NOW(), 2, 'xxxxxxxxxxxxxxxxxxxxxxx');

ALTER TABLE BLOG ADD TITLE VARCHAR(40) NULL;
ALTER TABLE BLOG ADD AUTHOR_ID int(11) NULL;


CREATE TABLE IF NOT EXISTS AUTHOR(
	ID INT(11) NOT NULL AUTO_INCREMENT,
	USER_NAME VARCHAR(64) NOT NULL,
	PASSWORD VARCHAR(64) NOT NULL,
	BIO VARCHAR(64) NULL DEFAULT NULL,
	EMAIL VARCHAR(64) NULL DEFAULT NULL,
	FAVOURITE_SECTION VARCHAR(64) NULL DEFAULT NULL,
	CREATE_DATE DATETIME(6) NULL DEFAULT NULL,
	EDIT_DATE DATETIME(6) NULL DEFAULT NULL,
	PRIMARY KEY (ID)
) DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

CREATE TABLE IF NOT EXISTS POST(
	ID INT(11) NOT NULL AUTO_INCREMENT,
	BLOG_ID INT(11) NOT NULL,
	AUTHOR_ID INT(64) NULL DEFAULT NULL,
	SECTION VARCHAR(64) NULL DEFAULT NULL,
	SUBJECT VARCHAR(64) NULL DEFAULT NULL,
	DRAFT VARCHAR(64) NULL DEFAULT NULL,
	BODY VARCHAR(1024) NULL DEFAULT NULL,
	CREATED_ON DATETIME(6) NULL DEFAULT NULL,
	EDIT_DATE DATETIME(6) NULL DEFAULT NULL,
	PRIMARY KEY (ID),
	CONSTRAINT `FK_POST_BLOG_ID` FOREIGN KEY (`BLOG_ID`) REFERENCES `BLOG` (`ID`) ON UPDATE NO ACTION ON DELETE NO ACTION,
	CONSTRAINT `FK_POST_AUTHOR_ID` FOREIGN KEY (`AUTHOR_ID`) REFERENCES `AUTHOR` (`ID`) ON UPDATE NO ACTION ON DELETE NO ACTION
) DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

CREATE TABLE IF NOT EXISTS COMMENTS(
	ID INT(11) NOT NULL AUTO_INCREMENT,
	POST_ID INT(11) NULL DEFAULT NULL,
	NAME VARCHAR(64) NULL DEFAULT NULL,
	COMMENT VARCHAR(256) NULL DEFAULT NULL,
	CREATE_DATE DATETIME(6) NULL DEFAULT NULL,
	EDIT_DATE DATETIME(6) NULL DEFAULT NULL,
	PRIMARY KEY (ID),
	CONSTRAINT `FK_COMMENT_POST_ID` FOREIGN KEY (`POST_ID`) REFERENCES `POST` (`ID`) ON UPDATE NO ACTION ON DELETE NO ACTION
) DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

CREATE TABLE IF NOT EXISTS TAG(
	ID INT(11) NOT NULL AUTO_INCREMENT,
	NAME INT(11) NULL DEFAULT NULL,
	CREATE_DATE DATETIME(6) NULL DEFAULT NULL,
	EDIT_DATE DATETIME(6) NULL DEFAULT NULL,
	PRIMARY KEY (ID)
) DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

CREATE TABLE IF NOT EXISTS POST_TAG(
	ID INT(11) NOT NULL AUTO_INCREMENT,
	POST_ID INT(11) NULL DEFAULT NULL,
	TAG_ID INT(11) NULL DEFAULT NULL,
	CREATE_DATE DATETIME(6) NULL DEFAULT NULL,
	EDIT_DATE DATETIME(6) NULL DEFAULT NULL,
	PRIMARY KEY (ID),
	CONSTRAINT `FK_POST_TAG_POST_ID` FOREIGN KEY (`POST_ID`) REFERENCES `POST` (`ID`) ON UPDATE NO ACTION ON DELETE NO ACTION,
	CONSTRAINT `FK_POST_TAG_TAG_ID` FOREIGN KEY (`TAG_ID`) REFERENCES `TAG` (`ID`) ON UPDATE NO ACTION ON DELETE NO ACTION
) DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;


